# This is an OpenAPI Specification (https://swagger.io/specification/)
# for the Personal Demographics Service (PDS) API
# owned by NHS Digital (https://digital.nhs.uk/)
openapi: "3.0.0"
info:
  version: "{VERSION}"
  title: Personal Demographics Service (FHIR) API
  description: |
    ## Overview
    Use this API to access the [Personal Demographics Service (PDS)](https://digital.nhs.uk/services/demographics) - the national electronic database of NHS patient details such as name, address, date of birth and NHS Number.

    You can:
    * search for patients
    * get patient details
    * update patient details

    You cannot currently use this API to:
    * check that you have the right NHS Number for a patient
    * create a new record for a birth
    * receive birth notifications
    * create a record for a new patient
    * register a new patient at a GP Practice - instead, use [National Health Application and Infrastructure Services (NHAIS)](https://digital.nhs.uk/services/nhais/nhais-developer-document-library)

    You can access the following data:
    * NHS Number
    * name
    * gender
    * addresses and contact details
    * birth information
    * death information
    * registered GP
    * nominated pharmacy (other related pharmacies coming soon)
    * consent information (coming soon)
    * related people (coming soon)

    ## API status
    This API is in [alpha](/reference-guide#api-status) - expect significant breaking changes.

    It is currently only available for sandbox testing, not for integration testing or production use.

    The following items are on our roadmap, in rough priority order:
    - addition of data fields for consent information, related people and more information on nominated pharmacies
    - move from alpha into beta
    - authorisation for NHS staff using OAuth 2.0 and NHS Identity
    - integration testing service (target date: end of February 2020)
    - assurance process
    - production service - beta - search for patient and retrieve patient details (target date: end of March 2020)
    - production service - beta - update patient (target date: end of April 2020)
    - unattended access - without smartcard - similar to the PDS SMSP API (target date to be confirmed)
    - access for citizens using NHS Login (target date to be confirmed)
    - exit beta (target date: end of September 2020, subject to availability of beta testers)

    We are extremely keen to receive feedback on the API during alpha and beta,
    for example if there are data fields missing that you think you need.
    Please [get in touch](/help-and-support) with any comments or suggestions.

    ## Technology
    This API is [RESTful](https://emea-demo8-nhsdportal.apigee.io/introduction-to-apis#basic-rest).

    This API is compliant with the
    [FHIR](https://emea-demo8-nhsdportal.apigee.io/introduction-to-apis#fhir-rest)
    standard for health care data exchange.
    Specifically, it complies with [FHIR R4](https://hl7.org/fhir/R4/).

    ## Authorisation
    This API is [user-restricted](https://emea-demo8-nhsdportal.apigee.io/security-and-authorisation#user-restricted-apis).
    It uses OAuth 2.0 to authorise both the calling system and end user.
    
    In can currently only be accessed by NHS staff, using NHS Identity. In due course we plan to add the following:
    - access for citizens, using NHS Login
    - unattended access - without smartcard - similar to the PDS SMSP API

    ## Related APIs
    The following APIs are also related to this API:

    [Organisation Data Service FHIR API](https://developer.nhs.uk/apis/ods/) - use this to get full details for the organisations related to the patient, such as their registered GP or nominated pharmacy.

    ## Testing
    You can test this API in:
    * our [sandbox environment](/testing#sandbox-testing) for initial developer testing
    * our [integration test environment](/testing#integration-testing) for formal integration testing (coming soon)

    Our sandbox environment is a very basic simulation of the live service. It only covers a limited set of scenarios and is stateless, so does not actually persist any updates.

    For more details on sandbox testing, or to try out the sandbox using our "Try this API" feature, see the documentation for each endpoint.

    Alternatively, you can try out the sandbox using our Postman collection:

    [![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/2871d49488699f3f5a67)

    ## Assurance
    We are hoping to make the assurance process as lightweight and as self-service as possible.
    
    More details to follow.

    ## Endpoints
    To see details for specific endpoints, select from the list on the left hand side of the page:
    * `GET /Patient` - search for patient
    * `GET /Patient/{nhs_number}` - get patient's personal details
    * `PATCH /Patient/{nhs_number}` - update patient's personal details
  contact:
    name: 'Personal Demographics Service FHIR API Support'
    url: 'https://tbc.api.nhs.net'
    email: 'tbc-api-support@nhs.net'

servers:
  - url: https://emea-demo8-test.apigee.net/personal-demographics
    description: Sandbox service.

tags:
  - name: patients

paths:
  /Patient:
    get:
      summary: Search for patient
      operationId: search-patient
      externalDocs:
        description: ODS codes and documentation.
        url: https://digital.nhs.uk/services/organisation-data-service
      description: |
        ## Overview
        Search for a patient.

        ## Search types
        This endpoint will search for a patient using one of four search types. The choice of search is automatic and will cascade as necessary until results are found. Searches are case-insensitive.

        ### Simple search
        The fastest match, requires family_name, first_name, gender, birth_date.
        Returns either a single matching patient or nothing. A limited set of parameters can be provided, all of which must exactly match the current information held.

        ### Advanced search
        Can return multiple matching patients if the information provided matches the current information held.
        Supports searching against additional information fields.
        Wildcards (\*) in name and postcode fields are supported.
        Wildcards must be preceeded by at least two characters, i.e. 'Br\*' is valid, but '\*cDougal' is not.
        Multiple wildcards are allowed, for example 'Br\*w\*' will match 'Brown' and 'Brower'.

        ### Advanced historic search
        Identical to advanced except it also searches historic patient data, for example previous names or addresses.

        ### Weighted search
        Returns a percentage match weight for each potentially matching patient. Always searches historical data. Requires at least one of the following combinations of search parameters:
          - family_name, first_name, gender, birth_date (or range)
          - family_name, gender, birth_date (or range), postcode
          - first_name, gender, birth_date (or range), postcode

        ## Sandbox testing
        You can test the following scenarios in our [sandbox environment](/testing#sandbox-testing):

        | Scenario                       | Request                                                      | Response                                   |
        | ------------------------------ | ------------------------------------------------------------ | ------------------------------------------ |
        | Successful simple search       | `family`=`Smith`, `given`=`Jane`, `gender`=`female`, `birthdate`=`2010-10-22` | HTTP Status 200 with single search result. |
        | Unsuccessful search            | Any other valid search query parameters                      | HTTP Status 200 with no search results     |
        | Invalid date format            | `birthdate` or `death-date` query parameters with values not in format `YYYY-MM-DD` | HTTP Status 400 with problem description   |
        | Too few search parameters      | Any invalid combination of query parameters                  | HTTP Status 400 with problem description   |

        You can try out the sandbox using the "Try this API" feature on the right hand side of this page.

        Alternatively, you can try out the sandbox using our Postman collection:

        [![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/2871d49488699f3f5a67)
      tags:
        - patients
      parameters:
        - name: family
          description: The patient's family name (surname).
          example: Smith
          in: query
          required: false
          schema:
            type: string
        - name: given
          description: The patient's given name(s).
          example: Jane
          in: query
          required: false
          schema:
            type: string
        - name: gender
          description: Gender with which the patient most strongly identifies.
          example: female
          in: query
          required: false
          schema:
            $ref: 'components/schemas/Gender.yaml'
        - name: birthdate
          in: query
          description: Birth date in the format `yyyy-mm-dd`. Required for simple searches. Other search types must provide either a birth date or a birth date range.
          example: "2010-10-22"
          required: false
          schema:
            type: string
            format: date
        - name: death-date
          in: query
          description: Date of death in the format `yyyy-mm-dd`.
          required: false
          example: "2018-03-20"
          schema:
            type: string
            format: date
            example: "2018-03-20"
        - name: address-postcode
          description: White spaces in postcodes are significant, i.e. LS16AE will not match LS1 6AE.
          example: LS1 6AE
          in: query
          required: false
          schema:
            type: string
        - name: organization
          description: The organisation code of the patient's registered general practice, as held in the [Organisation Data Service](https://developer.nhs.uk/apis/ods/).
          example: Y00001
          in: query
          required: false
          schema:
            type: string
            format: ods_code
            pattern: '^[A-Z]\d{5}$'
      responses:
        '200':
          description: A completed search, containing zero, one or many matching patients.
          content:
            application/fhir+json:
              schema:
                type: object
                properties:
                  resourceType:
                    type: string
                    description: FHIR Resource Type.
                    default: Bundle
                  type:
                    type: string
                    description: FHIR Bundle Type.
                    default: searchset
                  timestamp:
                    type: string
                    description: Time the search was performed.
                    format: datetime
                    example: '2019-12-25T12:00:00+00:00'
                  total:
                    type: integer
                    description: Number of resources returned in search.
                    example: 1
                  entry:
                    type: array
                    description: |
                      A list of matched patients. Empty if none found. For a simple search there is never more than one match.
                      For a weighted search, the patients are ordered by match weight, best first (based on the `score` field).
                    items:
                      type: object
                      properties:
                        fullUrl:
                          type: string
                          description: Absolute URL of the resource described in this item.
                          example: 'https://beta.api.digital.nhs.uk/Patient/9000000009'
                        search:
                          type: object
                          properties:
                            score:
                              description: Search score from 0.0 to 1.0.
                              type: number
                              minimum: 0.0
                              maximum: 1.0
                              example: 1.0
                        resource:
                          $ref: 'components/schemas/Patient.yaml'
              example:
                resourceType: Bundle
                type: searchset
                timestamp: '2019-12-25T12:00:00+00:00'
                total: 1
                entry:
                  - fullUrl: 'https://beta.api.digital.nhs.uk/Patient/9000000009'
                    search:
                      score: 1.0
                    resource:
                      $ref: 'components/examples/Patient.json'
        '400':
          description: Invalid search paramaters supplied.
          content:
            application/fhir+json:
              schema:
                $ref: 'components/schemas/OperationOutcome.yaml'
              examples:
                not-enough:
                  summary: too few search params
                  value:
                    resourceType: OperationOutcome
                    issue:
                      - severity: error
                        code: required
                        details:
                          coding:
                            - system: "https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode"
                              version: '1'
                              code: tooFewSearchParams
                              display: Not enough search parameters were provided to be able to make a search
                bad-dob:
                  summary: bad date of birth format
                  value:
                    resourceType: OperationOutcome
                    issue:
                      - severity: error
                        code: value
                        details:
                          coding:
                            - system: "https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode"
                              version: '1'
                              code: invalidDateFormat
                              display: "birthdate has invalid format: 2000 is not in YYYY-MM-DD format"
  /Patient/{nhs_number}:
    parameters:
      - $ref: '#/components/parameters/NhsNumber'
    get:
      description: |
        ## Overview
        Returns personal details for the patient with the given NHS Number.

        ## Sandbox test scenarios
        You can test the following scenarios in our sandbox environment:

        | Scenario              | Request                                         | Response                                      |
        | --------------------- | ----------------------------------------------- | --------------------------------------------- |
        | Patient exists        | `nhs_number`=`9000000009`                       | HTTP Status 200 with patient data in response |
        | Patient doesn't exist | `nhs_number`=`9111231130` (or any other valid NHS Number)  | HTTP Status 404 with problem description      |
        | Invalid NHS Number    | `nhs_number`=`9000000000` (or any invalid NHS Number)| HTTP Status 400 with problem description      |

        You can try out the sandbox using the "Try this API" feature on the right hand side of this page.

        Alternatively, you can try out the sandbox using our Postman collection:

        [![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/2871d49488699f3f5a67)

      summary: Retrieve a patient's record
      operationId: get-patient
      tags:
        - patients
      responses:
        '200':
          description: Information successfully returned.
          headers:
            ETag:
              $ref: 'components/schemas/ETag.yaml'
          content:
            application/fhir+json:
              schema:
                $ref: 'components/schemas/Patient.yaml'
              example:
                $ref: 'components/examples/Patient.json'
        '400':
          description: Invalid NHS number supplied.
          content:
            application/fhir+json:
              schema:
                $ref: 'components/schemas/OperationOutcome.yaml'
              example:
                resourceType: OperationOutcome
                issue:
                  - severity: error
                    code: value
                    details:
                      coding:
                        - system: "https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode"
                          version: '1'
                          code: invalidNHSNumber
                          display: NHS Number 9000000000 is not a valid NHS number
        '404':
          description: Patient not found.
          content:
            application/fhir+json:
              schema:
                $ref: 'components/schemas/OperationOutcome.yaml'
              example:
                resourceType: OperationOutcome
                issue:
                  - severity: error
                    code: not-found
                    details:
                      coding:
                        - system: "https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode"
                          version: '1'
                          code: patientNotFound
                          display: Patient with NHS number 9111231130 could not be found
    patch:
      description: |
        ## Overview
        Updates specific patient information.

        This is a 'patch' operation, meaning you can update specific parts of the patient record (such as a name or an address), as opposed to having to update the entire record.

        ## Patient record versioning
        To update a patient's record you must have retrieved it first.
        When you retrieve a patient record, you get a version number for the record (in the `ETag` header and in the `versionId` field in the response).
        You must then pass the record's version number in the update request (in the `If-Match` header).
        The update will only succeed if the patient record has not been updated in our database in the meantime.
        If the update succeeds, you will receive a copy of the update record in the response, including the new record version number.
        If you have a subsequent update you must use the new version number.

        ## Sandbox test scenarios
        You can test the following scenarios in our sandbox environment.
        Note that your changes will not be persisted.
        JSON Patch operations themselves are validated, but the resulting resource is not validated for correctness.

        | Scenario                            | Request                                                      | Response                                         |
        | ----------------------------------- | ------------------------------------------------------------ | ------------------------------------------------ |
        | Successful update                   | `nhs_number`=`9000000009`<br />Body: One of the provided examples<br />Headers: `If-Match`=`W/"2"`, `Content-Type`=`application/json-patch+json` | HTTP Status 200 with updated patient in response (but note that the update won't be persisted) |
        | Patient doesn't exist               | `nhs_number`=`9111231130` (or any other valid NHS Number)    | HTTP Status 404 with problem description         |
        | Invalid NHS Number                  | `nhs_number`=`9000000000` (or any invalid NHS Number)        | HTTP Status 400 with problem description         |
        | Missing resource version identifier | `If-Match` header missing or set to format other than `W/"<version>"` | HTTP Status 400 with problem description         |
        | Incorrect resource version          | `If-Match`=`W/"1"`                                           | HTTP Status 412 with problem description         |
        | Wrong content type                  | `Content-Type` header missing or other than `application/json-patch+json` | HTTP Status 415 with problem description         |
        | No patches sent                     | Send body with no `patches` attribute                        | HTTP Status 400 with problem description         |
        | Invalid patch operation(s)          | Send body with invalid JSON patches in `patches` attribute   | HTTP Status 400 with problem description         |

        You can try out the sandbox using the "Try this API" feature on the right hand side of this page.

        Alternatively, you can try out the sandbox using our Postman collection:

        [![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/2871d49488699f3f5a67)


      summary: Update a patient's record
      operationId: update-patient-partial
      tags:
        - patients
      externalDocs:
        description: IETF RFC 6902, which defines json-patch.
        url: https://tools.ietf.org/html/rfc6902
      parameters:
        - $ref: '#/components/parameters/IfMatch'
      requestBody:
        required: true
        content:
          # application/json-patch+json: FIXME - should be set to this but we have had to change it due to an Apigee SmartDocs bug.
          # See email chain w subject "Try this API feature for PATCH/POST APIs" between Alex H, Tony H, and David Macdonald from Apigee
          application/json:
            schema:
              type: object
              required:
                - patches
              properties:
                correction:
                  description: Set to true if the update is correcting previously incorrect data.
                  type: boolean
                  default: false
                patches:
                  $ref: 'components/schemas/JsonPatch.yaml'
            examples:
              add-name:
                summary: Add a new name to the patient
                value:
                  $ref: 'components/examples/requests/PatientPatch/add-name.json'
              update-name:
                summary: Update the first given name entry
                value:
                  $ref: 'components/examples/requests/PatientPatch/update-name.json'
              delete-name:
                summary: Remove a name no longer in use
                value:
                  $ref: 'components/examples/requests/PatientPatch/delete-name.json'
      responses:
        '200':
          description: Patient updated.
          headers:
            ETag:
              $ref: 'components/schemas/ETag.yaml'
          content:
            application/fhir+json:
              schema:
                $ref: 'components/schemas/Patient.yaml'
        '400':
          description: Client error.
          content:
            application/fhir+json:
              schema:
                $ref: 'components/schemas/OperationOutcome.yaml'
              examples:
                missing-if-match:
                  summary: Missing If-Match header
                  value:
                    resourceType: OperationOutcome
                    issue:
                      - severity: error
                        code: required
                        details:
                          coding:
                            - system: "https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode"
                              version: '1'
                              code: versionNotSupplied
                              display: If-Match header must be supplied to update this resource
                invalid-nhs-number:
                  summary: Invalid NHS number supplied
                  value:
                    resourceType: OperationOutcome
                    issue:
                      - severity: error
                        code: value
                        details:
                          coding:
                            - system: "https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode"
                              version: '1'
                              code: invalidNHSNumber
                              display: NHS Number 9000000000 is not a valid NHS number
                no-patches-submitted:
                  summary: No patches submitted
                  value:
                    resourceType: OperationOutcome
                    issue:
                      - severity: error
                        code: required
                        details:
                          coding:
                            - system: "https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode"
                              version: '1'
                              code: noPatchesSubmitted
                              display: No patches submitted
                invalid-patch-operation:
                  summary: Invalid patch operation(s)
                  value:
                    resourceType: OperationOutcome
                    issue:
                      - severity: error
                        code: value
                        details:
                          coding:
                            - system: "https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode"
                              version: '1'
                              code: invalidPatchOperation
                              display: "Invalid patch: Cannot perform the operation at a path that does not exist"
        '404':
          description: Patient not found.
          content:
            application/fhir+json:
              schema:
                $ref: 'components/schemas/OperationOutcome.yaml'
              example:
                resourceType: OperationOutcome
                issue:
                  - severity: error
                    code: not-found
                    details:
                      coding:
                        - system: "https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode"
                          version: '1'
                          code: patientNotFound
                          display: Patient with NHS number 9111231130 could not be found
        '412':
          $ref: '#/components/responses/412PreconditionFailed'
        '415':
          description: Unsupported media type.
          content:
            application/fhir+json:
              schema:
                $ref: 'components/schemas/OperationOutcome.yaml'
              example:
                resourceType: OperationOutcome
                issue:
                  - severity: error
                    code: value
                    details:
                      coding:
                        - system: "https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode"
                          version: '1'
                          code: unsupportedMediaType
                          display: Must be application/json-patch+json
components:
  parameters:
    NhsNumber:
      name: nhs_number
      in: path
      description: The patient's NHS Number.
      required: true
      schema:
        $ref: 'components/schemas/NhsNumber.yaml'
    IfMatch:
      in: header
      name: If-Match
      description: |
        Latest known version identifier enclosed in quotes preceded by `W/`.

        Send the value of this resource's `ETag` response header (or `meta.versionId` property) as received.
      required: true
      schema:
        type: string
        format: '^W\/\"[[:print:]]+\"$' # Printable characters enclosed in quotes. See: https://tools.ietf.org/html/rfc7230#section-3.2.6
        example: W/"2"
  schemas:
    Patient:
      $ref: 'components/schemas/Patient.yaml'
    OperationOutcome:
      $ref: 'components/schemas/OperationOutcome.yaml'
  responses:
    412PreconditionFailed:
      description: |
        Precondition failed.

        The version identifier submitted in the `If-Match` header was not the latest version of the resource.
      content:
        application/fhir+json:
          schema:
            $ref: 'components/schemas/OperationOutcome.yaml'
          example:
            resourceType: OperationOutcome
            issue:
              - severity: error
                code: conflict
                details:
                  coding:
                    - system: "https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode"
                      version: '1'
                      code: versionMismatch
                      display: This resource has changed since you last read. Please re-read and try again with the new version number.
